// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: echodms.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentFormat int32

const (
	DocumentFormat_DOCUMENT_FORMAT_UNSPECIFIED DocumentFormat = 0
	DocumentFormat_TYPST                       DocumentFormat = 1
	DocumentFormat_LATEX                       DocumentFormat = 2
	DocumentFormat_MARKDOWN                    DocumentFormat = 3
)

// Enum value maps for DocumentFormat.
var (
	DocumentFormat_name = map[int32]string{
		0: "DOCUMENT_FORMAT_UNSPECIFIED",
		1: "TYPST",
		2: "LATEX",
		3: "MARKDOWN",
	}
	DocumentFormat_value = map[string]int32{
		"DOCUMENT_FORMAT_UNSPECIFIED": 0,
		"TYPST":                       1,
		"LATEX":                       2,
		"MARKDOWN":                    3,
	}
)

func (x DocumentFormat) Enum() *DocumentFormat {
	p := new(DocumentFormat)
	*p = x
	return p
}

func (x DocumentFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_echodms_proto_enumTypes[0].Descriptor()
}

func (DocumentFormat) Type() protoreflect.EnumType {
	return &file_echodms_proto_enumTypes[0]
}

func (x DocumentFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentFormat.Descriptor instead.
func (DocumentFormat) EnumDescriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{0}
}

type CompilerName int32

const (
	CompilerName_COMPILER_NAME_UNSPECIFIED CompilerName = 0
	CompilerName_TYPST_COMPILER            CompilerName = 1
	CompilerName_PDFLATEX                  CompilerName = 2
	CompilerName_XELATEX                   CompilerName = 3
	CompilerName_LUALATEX                  CompilerName = 4
	CompilerName_PANDOC                    CompilerName = 5
)

// Enum value maps for CompilerName.
var (
	CompilerName_name = map[int32]string{
		0: "COMPILER_NAME_UNSPECIFIED",
		1: "TYPST_COMPILER",
		2: "PDFLATEX",
		3: "XELATEX",
		4: "LUALATEX",
		5: "PANDOC",
	}
	CompilerName_value = map[string]int32{
		"COMPILER_NAME_UNSPECIFIED": 0,
		"TYPST_COMPILER":            1,
		"PDFLATEX":                  2,
		"XELATEX":                   3,
		"LUALATEX":                  4,
		"PANDOC":                    5,
	}
)

func (x CompilerName) Enum() *CompilerName {
	p := new(CompilerName)
	*p = x
	return p
}

func (x CompilerName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompilerName) Descriptor() protoreflect.EnumDescriptor {
	return file_echodms_proto_enumTypes[1].Descriptor()
}

func (CompilerName) Type() protoreflect.EnumType {
	return &file_echodms_proto_enumTypes[1]
}

func (x CompilerName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompilerName.Descriptor instead.
func (CompilerName) EnumDescriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{1}
}

type OutputFormat int32

const (
	OutputFormat_OUTPUT_FORMAT_UNSPECIFIED OutputFormat = 0
	OutputFormat_PDF                       OutputFormat = 1
	OutputFormat_PNG                       OutputFormat = 2
	OutputFormat_SVG                       OutputFormat = 3
	OutputFormat_HTML                      OutputFormat = 4
)

// Enum value maps for OutputFormat.
var (
	OutputFormat_name = map[int32]string{
		0: "OUTPUT_FORMAT_UNSPECIFIED",
		1: "PDF",
		2: "PNG",
		3: "SVG",
		4: "HTML",
	}
	OutputFormat_value = map[string]int32{
		"OUTPUT_FORMAT_UNSPECIFIED": 0,
		"PDF":                       1,
		"PNG":                       2,
		"SVG":                       3,
		"HTML":                      4,
	}
)

func (x OutputFormat) Enum() *OutputFormat {
	p := new(OutputFormat)
	*p = x
	return p
}

func (x OutputFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_echodms_proto_enumTypes[2].Descriptor()
}

func (OutputFormat) Type() protoreflect.EnumType {
	return &file_echodms_proto_enumTypes[2]
}

func (x OutputFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputFormat.Descriptor instead.
func (OutputFormat) EnumDescriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{2}
}

type CollaboratorRole int32

const (
	CollaboratorRole_COLLABORATOR_ROLE_UNSPECIFIED CollaboratorRole = 0
	CollaboratorRole_ADMIN                         CollaboratorRole = 1
	CollaboratorRole_EDITOR                        CollaboratorRole = 2
	CollaboratorRole_VIEWER                        CollaboratorRole = 3
)

// Enum value maps for CollaboratorRole.
var (
	CollaboratorRole_name = map[int32]string{
		0: "COLLABORATOR_ROLE_UNSPECIFIED",
		1: "ADMIN",
		2: "EDITOR",
		3: "VIEWER",
	}
	CollaboratorRole_value = map[string]int32{
		"COLLABORATOR_ROLE_UNSPECIFIED": 0,
		"ADMIN":                         1,
		"EDITOR":                        2,
		"VIEWER":                        3,
	}
)

func (x CollaboratorRole) Enum() *CollaboratorRole {
	p := new(CollaboratorRole)
	*p = x
	return p
}

func (x CollaboratorRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollaboratorRole) Descriptor() protoreflect.EnumDescriptor {
	return file_echodms_proto_enumTypes[3].Descriptor()
}

func (CollaboratorRole) Type() protoreflect.EnumType {
	return &file_echodms_proto_enumTypes[3]
}

func (x CollaboratorRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollaboratorRole.Descriptor instead.
func (CollaboratorRole) EnumDescriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{3}
}

type CollaboratorStatus int32

const (
	CollaboratorStatus_COLLABORATOR_STATUS_UNSPECIFIED CollaboratorStatus = 0
	CollaboratorStatus_INVITED                         CollaboratorStatus = 1
	CollaboratorStatus_ACCEPTED                        CollaboratorStatus = 2
	CollaboratorStatus_PENDING                         CollaboratorStatus = 3
	CollaboratorStatus_DECLINED                        CollaboratorStatus = 4
	CollaboratorStatus_BLOCKED                         CollaboratorStatus = 5
)

// Enum value maps for CollaboratorStatus.
var (
	CollaboratorStatus_name = map[int32]string{
		0: "COLLABORATOR_STATUS_UNSPECIFIED",
		1: "INVITED",
		2: "ACCEPTED",
		3: "PENDING",
		4: "DECLINED",
		5: "BLOCKED",
	}
	CollaboratorStatus_value = map[string]int32{
		"COLLABORATOR_STATUS_UNSPECIFIED": 0,
		"INVITED":                         1,
		"ACCEPTED":                        2,
		"PENDING":                         3,
		"DECLINED":                        4,
		"BLOCKED":                         5,
	}
)

func (x CollaboratorStatus) Enum() *CollaboratorStatus {
	p := new(CollaboratorStatus)
	*p = x
	return p
}

func (x CollaboratorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollaboratorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_echodms_proto_enumTypes[4].Descriptor()
}

func (CollaboratorStatus) Type() protoreflect.EnumType {
	return &file_echodms_proto_enumTypes[4]
}

func (x CollaboratorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollaboratorStatus.Descriptor instead.
func (CollaboratorStatus) EnumDescriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{4}
}

type Document struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Format          DocumentFormat         `protobuf:"varint,4,opt,name=format,proto3,enum=echoDMS.DocumentFormat" json:"format,omitempty"`
	Compiler        CompilerName           `protobuf:"varint,5,opt,name=compiler,proto3,enum=echoDMS.CompilerName" json:"compiler,omitempty"`
	CompilerVersion string                 `protobuf:"bytes,6,opt,name=compiler_version,json=compilerVersion,proto3" json:"compiler_version,omitempty"`
	OutputFormat    OutputFormat           `protobuf:"varint,7,opt,name=output_format,json=outputFormat,proto3,enum=echoDMS.OutputFormat" json:"output_format,omitempty"`
	OwnerId         string                 `protobuf:"bytes,8,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	IsArchived      bool                   `protobuf:"varint,9,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_echodms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Document) GetFormat() DocumentFormat {
	if x != nil {
		return x.Format
	}
	return DocumentFormat_DOCUMENT_FORMAT_UNSPECIFIED
}

func (x *Document) GetCompiler() CompilerName {
	if x != nil {
		return x.Compiler
	}
	return CompilerName_COMPILER_NAME_UNSPECIFIED
}

func (x *Document) GetCompilerVersion() string {
	if x != nil {
		return x.CompilerVersion
	}
	return ""
}

func (x *Document) GetOutputFormat() OutputFormat {
	if x != nil {
		return x.OutputFormat
	}
	return OutputFormat_OUTPUT_FORMAT_UNSPECIFIED
}

func (x *Document) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Document) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_echodms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{1}
}

func (x *Page) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Page) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Page) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Page) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Page) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Page) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DocumentCollaborator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          CollaboratorRole       `protobuf:"varint,4,opt,name=role,proto3,enum=echoDMS.CollaboratorRole" json:"role,omitempty"`
	Status        CollaboratorStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=echoDMS.CollaboratorStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentCollaborator) Reset() {
	*x = DocumentCollaborator{}
	mi := &file_echodms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentCollaborator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentCollaborator) ProtoMessage() {}

func (x *DocumentCollaborator) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentCollaborator.ProtoReflect.Descriptor instead.
func (*DocumentCollaborator) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentCollaborator) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentCollaborator) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentCollaborator) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DocumentCollaborator) GetRole() CollaboratorRole {
	if x != nil {
		return x.Role
	}
	return CollaboratorRole_COLLABORATOR_ROLE_UNSPECIFIED
}

func (x *DocumentCollaborator) GetStatus() CollaboratorStatus {
	if x != nil {
		return x.Status
	}
	return CollaboratorStatus_COLLABORATOR_STATUS_UNSPECIFIED
}

func (x *DocumentCollaborator) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DocumentVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	VersionNumber int32                  `protobuf:"varint,3,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	Snapshot      string                 `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"` // JSON string
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentVersion) Reset() {
	*x = DocumentVersion{}
	mi := &file_echodms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentVersion) ProtoMessage() {}

func (x *DocumentVersion) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentVersion.ProtoReflect.Descriptor instead.
func (*DocumentVersion) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{3}
}

func (x *DocumentVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentVersion) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentVersion) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *DocumentVersion) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *DocumentVersion) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *DocumentVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CompiledOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	VersionId     string                 `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	OutputFormat  OutputFormat           `protobuf:"varint,4,opt,name=output_format,json=outputFormat,proto3,enum=echoDMS.OutputFormat" json:"output_format,omitempty"`
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSizeBytes int64                  `protobuf:"varint,6,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	CompiledAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=compiled_at,json=compiledAt,proto3" json:"compiled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledOutput) Reset() {
	*x = CompiledOutput{}
	mi := &file_echodms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledOutput) ProtoMessage() {}

func (x *CompiledOutput) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledOutput.ProtoReflect.Descriptor instead.
func (*CompiledOutput) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{4}
}

func (x *CompiledOutput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompiledOutput) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CompiledOutput) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *CompiledOutput) GetOutputFormat() OutputFormat {
	if x != nil {
		return x.OutputFormat
	}
	return OutputFormat_OUTPUT_FORMAT_UNSPECIFIED
}

func (x *CompiledOutput) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CompiledOutput) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *CompiledOutput) GetCompiledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompiledAt
	}
	return nil
}

type GetPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageRequest) Reset() {
	*x = GetPageRequest{}
	mi := &file_echodms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageRequest) ProtoMessage() {}

func (x *GetPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageRequest.ProtoReflect.Descriptor instead.
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{5}
}

func (x *GetPageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesRequest) Reset() {
	*x = ListPagesRequest{}
	mi := &file_echodms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesRequest) ProtoMessage() {}

func (x *ListPagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesRequest.ProtoReflect.Descriptor instead.
func (*ListPagesRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{6}
}

func (x *ListPagesRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ListPagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*Page                `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesResponse) Reset() {
	*x = ListPagesResponse{}
	mi := &file_echodms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesResponse) ProtoMessage() {}

func (x *ListPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesResponse.ProtoReflect.Descriptor instead.
func (*ListPagesResponse) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{7}
}

func (x *ListPagesResponse) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

type CreatePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePageRequest) Reset() {
	*x = CreatePageRequest{}
	mi := &file_echodms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageRequest) ProtoMessage() {}

func (x *CreatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageRequest.ProtoReflect.Descriptor instead.
func (*CreatePageRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePageRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CreatePageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePageRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdatePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePageRequest) Reset() {
	*x = UpdatePageRequest{}
	mi := &file_echodms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePageRequest) ProtoMessage() {}

func (x *UpdatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePageRequest.ProtoReflect.Descriptor instead.
func (*UpdatePageRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdatePageRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type DeletePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePageRequest) Reset() {
	*x = DeletePageRequest{}
	mi := &file_echodms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePageRequest) ProtoMessage() {}

func (x *DeletePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePageRequest.ProtoReflect.Descriptor instead.
func (*DeletePageRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCollaboratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollaboratorRequest) Reset() {
	*x = GetCollaboratorRequest{}
	mi := &file_echodms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollaboratorRequest) ProtoMessage() {}

func (x *GetCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*GetCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{11}
}

func (x *GetCollaboratorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCollaboratorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollaboratorsRequest) Reset() {
	*x = ListCollaboratorsRequest{}
	mi := &file_echodms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollaboratorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollaboratorsRequest) ProtoMessage() {}

func (x *ListCollaboratorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollaboratorsRequest.ProtoReflect.Descriptor instead.
func (*ListCollaboratorsRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{12}
}

func (x *ListCollaboratorsRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ListCollaboratorsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Collaborators []*DocumentCollaborator `protobuf:"bytes,1,rep,name=collaborators,proto3" json:"collaborators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollaboratorsResponse) Reset() {
	*x = ListCollaboratorsResponse{}
	mi := &file_echodms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollaboratorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollaboratorsResponse) ProtoMessage() {}

func (x *ListCollaboratorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollaboratorsResponse.ProtoReflect.Descriptor instead.
func (*ListCollaboratorsResponse) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{13}
}

func (x *ListCollaboratorsResponse) GetCollaborators() []*DocumentCollaborator {
	if x != nil {
		return x.Collaborators
	}
	return nil
}

type AddCollaboratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          CollaboratorRole       `protobuf:"varint,3,opt,name=role,proto3,enum=echoDMS.CollaboratorRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCollaboratorRequest) Reset() {
	*x = AddCollaboratorRequest{}
	mi := &file_echodms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCollaboratorRequest) ProtoMessage() {}

func (x *AddCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*AddCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{14}
}

func (x *AddCollaboratorRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *AddCollaboratorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddCollaboratorRequest) GetRole() CollaboratorRole {
	if x != nil {
		return x.Role
	}
	return CollaboratorRole_COLLABORATOR_ROLE_UNSPECIFIED
}

type UpdateCollaboratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          CollaboratorRole       `protobuf:"varint,2,opt,name=role,proto3,enum=echoDMS.CollaboratorRole" json:"role,omitempty"`
	Status        CollaboratorStatus     `protobuf:"varint,3,opt,name=status,proto3,enum=echoDMS.CollaboratorStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollaboratorRequest) Reset() {
	*x = UpdateCollaboratorRequest{}
	mi := &file_echodms_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollaboratorRequest) ProtoMessage() {}

func (x *UpdateCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateCollaboratorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCollaboratorRequest) GetRole() CollaboratorRole {
	if x != nil {
		return x.Role
	}
	return CollaboratorRole_COLLABORATOR_ROLE_UNSPECIFIED
}

func (x *UpdateCollaboratorRequest) GetStatus() CollaboratorStatus {
	if x != nil {
		return x.Status
	}
	return CollaboratorStatus_COLLABORATOR_STATUS_UNSPECIFIED
}

type RemoveCollaboratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCollaboratorRequest) Reset() {
	*x = RemoveCollaboratorRequest{}
	mi := &file_echodms_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCollaboratorRequest) ProtoMessage() {}

func (x *RemoveCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*RemoveCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveCollaboratorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_echodms_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{17}
}

func (x *GetVersionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_echodms_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{18}
}

func (x *ListVersionsRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*DocumentVersion     `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_echodms_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{19}
}

func (x *ListVersionsResponse) GetVersions() []*DocumentVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type CreateVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Snapshot      string                 `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVersionRequest) Reset() {
	*x = CreateVersionRequest{}
	mi := &file_echodms_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest) ProtoMessage() {}

func (x *CreateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{20}
}

func (x *CreateVersionRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CreateVersionRequest) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *CreateVersionRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type GetCompiledOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompiledOutputRequest) Reset() {
	*x = GetCompiledOutputRequest{}
	mi := &file_echodms_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompiledOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompiledOutputRequest) ProtoMessage() {}

func (x *GetCompiledOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompiledOutputRequest.ProtoReflect.Descriptor instead.
func (*GetCompiledOutputRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{21}
}

func (x *GetCompiledOutputRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCompiledOutputsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompiledOutputsRequest) Reset() {
	*x = ListCompiledOutputsRequest{}
	mi := &file_echodms_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompiledOutputsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompiledOutputsRequest) ProtoMessage() {}

func (x *ListCompiledOutputsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompiledOutputsRequest.ProtoReflect.Descriptor instead.
func (*ListCompiledOutputsRequest) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{22}
}

func (x *ListCompiledOutputsRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ListCompiledOutputsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*CompiledOutput      `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompiledOutputsResponse) Reset() {
	*x = ListCompiledOutputsResponse{}
	mi := &file_echodms_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompiledOutputsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompiledOutputsResponse) ProtoMessage() {}

func (x *ListCompiledOutputsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echodms_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompiledOutputsResponse.ProtoReflect.Descriptor instead.
func (*ListCompiledOutputsResponse) Descriptor() ([]byte, []int) {
	return file_echodms_proto_rawDescGZIP(), []int{23}
}

func (x *ListCompiledOutputsResponse) GetOutputs() []*CompiledOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_echodms_proto protoreflect.FileDescriptor

const file_echodms_proto_rawDesc = "" +
	"\n" +
	"\rechodms.proto\x12\aechoDMS\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xcf\x03\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12/\n" +
	"\x06format\x18\x04 \x01(\x0e2\x17.echoDMS.DocumentFormatR\x06format\x121\n" +
	"\bcompiler\x18\x05 \x01(\x0e2\x15.echoDMS.CompilerNameR\bcompiler\x12)\n" +
	"\x10compiler_version\x18\x06 \x01(\tR\x0fcompilerVersion\x12:\n" +
	"\routput_format\x18\a \x01(\x0e2\x15.echoDMS.OutputFormatR\foutputFormat\x12\x19\n" +
	"\bowner_id\x18\b \x01(\tR\aownerId\x12\x1f\n" +
	"\vis_archived\x18\t \x01(\bR\n" +
	"isArchived\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe6\x01\n" +
	"\x04Page\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xff\x01\n" +
	"\x14DocumentCollaborator\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12-\n" +
	"\x04role\x18\x04 \x01(\x0e2\x19.echoDMS.CollaboratorRoleR\x04role\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.echoDMS.CollaboratorStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xdf\x01\n" +
	"\x0fDocumentVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12%\n" +
	"\x0eversion_number\x18\x03 \x01(\x05R\rversionNumber\x12\x1a\n" +
	"\bsnapshot\x18\x04 \x01(\tR\bsnapshot\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9e\x02\n" +
	"\x0eCompiledOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\tR\tversionId\x12:\n" +
	"\routput_format\x18\x04 \x01(\x0e2\x15.echoDMS.OutputFormatR\foutputFormat\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12&\n" +
	"\x0ffile_size_bytes\x18\x06 \x01(\x03R\rfileSizeBytes\x12;\n" +
	"\vcompiled_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"compiledAt\" \n" +
	"\x0eGetPageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x10ListPagesRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"8\n" +
	"\x11ListPagesResponse\x12#\n" +
	"\x05pages\x18\x01 \x03(\v2\r.echoDMS.PageR\x05pages\"m\n" +
	"\x11CreatePageRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"\\\n" +
	"\x11UpdatePageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"#\n" +
	"\x11DeletePageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16GetCollaboratorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x18ListCollaboratorsRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"`\n" +
	"\x19ListCollaboratorsResponse\x12C\n" +
	"\rcollaborators\x18\x01 \x03(\v2\x1d.echoDMS.DocumentCollaboratorR\rcollaborators\"\x81\x01\n" +
	"\x16AddCollaboratorRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12-\n" +
	"\x04role\x18\x03 \x01(\x0e2\x19.echoDMS.CollaboratorRoleR\x04role\"\x8f\x01\n" +
	"\x19UpdateCollaboratorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04role\x18\x02 \x01(\x0e2\x19.echoDMS.CollaboratorRoleR\x04role\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.echoDMS.CollaboratorStatusR\x06status\"+\n" +
	"\x19RemoveCollaboratorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11GetVersionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x13ListVersionsRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"L\n" +
	"\x14ListVersionsResponse\x124\n" +
	"\bversions\x18\x01 \x03(\v2\x18.echoDMS.DocumentVersionR\bversions\"r\n" +
	"\x14CreateVersionRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1a\n" +
	"\bsnapshot\x18\x02 \x01(\tR\bsnapshot\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\"*\n" +
	"\x18GetCompiledOutputRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x1aListCompiledOutputsRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"P\n" +
	"\x1bListCompiledOutputsResponse\x121\n" +
	"\aoutputs\x18\x01 \x03(\v2\x17.echoDMS.CompiledOutputR\aoutputs*U\n" +
	"\x0eDocumentFormat\x12\x1f\n" +
	"\x1bDOCUMENT_FORMAT_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05TYPST\x10\x01\x12\t\n" +
	"\x05LATEX\x10\x02\x12\f\n" +
	"\bMARKDOWN\x10\x03*v\n" +
	"\fCompilerName\x12\x1d\n" +
	"\x19COMPILER_NAME_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTYPST_COMPILER\x10\x01\x12\f\n" +
	"\bPDFLATEX\x10\x02\x12\v\n" +
	"\aXELATEX\x10\x03\x12\f\n" +
	"\bLUALATEX\x10\x04\x12\n" +
	"\n" +
	"\x06PANDOC\x10\x05*R\n" +
	"\fOutputFormat\x12\x1d\n" +
	"\x19OUTPUT_FORMAT_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03PDF\x10\x01\x12\a\n" +
	"\x03PNG\x10\x02\x12\a\n" +
	"\x03SVG\x10\x03\x12\b\n" +
	"\x04HTML\x10\x04*X\n" +
	"\x10CollaboratorRole\x12!\n" +
	"\x1dCOLLABORATOR_ROLE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ADMIN\x10\x01\x12\n" +
	"\n" +
	"\x06EDITOR\x10\x02\x12\n" +
	"\n" +
	"\x06VIEWER\x10\x03*|\n" +
	"\x12CollaboratorStatus\x12#\n" +
	"\x1fCOLLABORATOR_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aINVITED\x10\x01\x12\f\n" +
	"\bACCEPTED\x10\x02\x12\v\n" +
	"\aPENDING\x10\x03\x12\f\n" +
	"\bDECLINED\x10\x04\x12\v\n" +
	"\aBLOCKED\x10\x052\xb8\x02\n" +
	"\vPageService\x127\n" +
	"\n" +
	"CreatePage\x12\x1a.echoDMS.CreatePageRequest\x1a\r.echoDMS.Page\x121\n" +
	"\aGetPage\x12\x17.echoDMS.GetPageRequest\x1a\r.echoDMS.Page\x12B\n" +
	"\tListPages\x12\x19.echoDMS.ListPagesRequest\x1a\x1a.echoDMS.ListPagesResponse\x127\n" +
	"\n" +
	"UpdatePage\x12\x1a.echoDMS.UpdatePageRequest\x1a\r.echoDMS.Page\x12@\n" +
	"\n" +
	"DeletePage\x12\x1a.echoDMS.DeletePageRequest\x1a\x16.google.protobuf.Empty2\xc2\x03\n" +
	"\x13CollaboratorService\x12Q\n" +
	"\x0fAddCollaborator\x12\x1f.echoDMS.AddCollaboratorRequest\x1a\x1d.echoDMS.DocumentCollaborator\x12Q\n" +
	"\x0fGetCollaborator\x12\x1f.echoDMS.GetCollaboratorRequest\x1a\x1d.echoDMS.DocumentCollaborator\x12Z\n" +
	"\x11ListCollaborators\x12!.echoDMS.ListCollaboratorsRequest\x1a\".echoDMS.ListCollaboratorsResponse\x12W\n" +
	"\x12UpdateCollaborator\x12\".echoDMS.UpdateCollaboratorRequest\x1a\x1d.echoDMS.DocumentCollaborator\x12P\n" +
	"\x12RemoveCollaborator\x12\".echoDMS.RemoveCollaboratorRequest\x1a\x16.google.protobuf.Empty2\xeb\x01\n" +
	"\x0eVersionService\x12H\n" +
	"\rCreateVersion\x12\x1d.echoDMS.CreateVersionRequest\x1a\x18.echoDMS.DocumentVersion\x12B\n" +
	"\n" +
	"GetVersion\x12\x1a.echoDMS.GetVersionRequest\x1a\x18.echoDMS.DocumentVersion\x12K\n" +
	"\fListVersions\x12\x1c.echoDMS.ListVersionsRequest\x1a\x1d.echoDMS.ListVersionsResponse2\xca\x01\n" +
	"\x15CompiledOutputService\x12O\n" +
	"\x11GetCompiledOutput\x12!.echoDMS.GetCompiledOutputRequest\x1a\x17.echoDMS.CompiledOutput\x12`\n" +
	"\x13ListCompiledOutputs\x12#.echoDMS.ListCompiledOutputsRequest\x1a$.echoDMS.ListCompiledOutputsResponseB Z\x1egithub.com/echoDMS/internal/pbb\x06proto3"

var (
	file_echodms_proto_rawDescOnce sync.Once
	file_echodms_proto_rawDescData []byte
)

func file_echodms_proto_rawDescGZIP() []byte {
	file_echodms_proto_rawDescOnce.Do(func() {
		file_echodms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echodms_proto_rawDesc), len(file_echodms_proto_rawDesc)))
	})
	return file_echodms_proto_rawDescData
}

var file_echodms_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_echodms_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_echodms_proto_goTypes = []any{
	(DocumentFormat)(0),                 // 0: echoDMS.DocumentFormat
	(CompilerName)(0),                   // 1: echoDMS.CompilerName
	(OutputFormat)(0),                   // 2: echoDMS.OutputFormat
	(CollaboratorRole)(0),               // 3: echoDMS.CollaboratorRole
	(CollaboratorStatus)(0),             // 4: echoDMS.CollaboratorStatus
	(*Document)(nil),                    // 5: echoDMS.Document
	(*Page)(nil),                        // 6: echoDMS.Page
	(*DocumentCollaborator)(nil),        // 7: echoDMS.DocumentCollaborator
	(*DocumentVersion)(nil),             // 8: echoDMS.DocumentVersion
	(*CompiledOutput)(nil),              // 9: echoDMS.CompiledOutput
	(*GetPageRequest)(nil),              // 10: echoDMS.GetPageRequest
	(*ListPagesRequest)(nil),            // 11: echoDMS.ListPagesRequest
	(*ListPagesResponse)(nil),           // 12: echoDMS.ListPagesResponse
	(*CreatePageRequest)(nil),           // 13: echoDMS.CreatePageRequest
	(*UpdatePageRequest)(nil),           // 14: echoDMS.UpdatePageRequest
	(*DeletePageRequest)(nil),           // 15: echoDMS.DeletePageRequest
	(*GetCollaboratorRequest)(nil),      // 16: echoDMS.GetCollaboratorRequest
	(*ListCollaboratorsRequest)(nil),    // 17: echoDMS.ListCollaboratorsRequest
	(*ListCollaboratorsResponse)(nil),   // 18: echoDMS.ListCollaboratorsResponse
	(*AddCollaboratorRequest)(nil),      // 19: echoDMS.AddCollaboratorRequest
	(*UpdateCollaboratorRequest)(nil),   // 20: echoDMS.UpdateCollaboratorRequest
	(*RemoveCollaboratorRequest)(nil),   // 21: echoDMS.RemoveCollaboratorRequest
	(*GetVersionRequest)(nil),           // 22: echoDMS.GetVersionRequest
	(*ListVersionsRequest)(nil),         // 23: echoDMS.ListVersionsRequest
	(*ListVersionsResponse)(nil),        // 24: echoDMS.ListVersionsResponse
	(*CreateVersionRequest)(nil),        // 25: echoDMS.CreateVersionRequest
	(*GetCompiledOutputRequest)(nil),    // 26: echoDMS.GetCompiledOutputRequest
	(*ListCompiledOutputsRequest)(nil),  // 27: echoDMS.ListCompiledOutputsRequest
	(*ListCompiledOutputsResponse)(nil), // 28: echoDMS.ListCompiledOutputsResponse
	(*timestamppb.Timestamp)(nil),       // 29: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 30: google.protobuf.Empty
}
var file_echodms_proto_depIdxs = []int32{
	0,  // 0: echoDMS.Document.format:type_name -> echoDMS.DocumentFormat
	1,  // 1: echoDMS.Document.compiler:type_name -> echoDMS.CompilerName
	2,  // 2: echoDMS.Document.output_format:type_name -> echoDMS.OutputFormat
	29, // 3: echoDMS.Document.created_at:type_name -> google.protobuf.Timestamp
	29, // 4: echoDMS.Document.updated_at:type_name -> google.protobuf.Timestamp
	29, // 5: echoDMS.Page.created_at:type_name -> google.protobuf.Timestamp
	29, // 6: echoDMS.Page.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 7: echoDMS.DocumentCollaborator.role:type_name -> echoDMS.CollaboratorRole
	4,  // 8: echoDMS.DocumentCollaborator.status:type_name -> echoDMS.CollaboratorStatus
	29, // 9: echoDMS.DocumentCollaborator.created_at:type_name -> google.protobuf.Timestamp
	29, // 10: echoDMS.DocumentVersion.created_at:type_name -> google.protobuf.Timestamp
	2,  // 11: echoDMS.CompiledOutput.output_format:type_name -> echoDMS.OutputFormat
	29, // 12: echoDMS.CompiledOutput.compiled_at:type_name -> google.protobuf.Timestamp
	6,  // 13: echoDMS.ListPagesResponse.pages:type_name -> echoDMS.Page
	7,  // 14: echoDMS.ListCollaboratorsResponse.collaborators:type_name -> echoDMS.DocumentCollaborator
	3,  // 15: echoDMS.AddCollaboratorRequest.role:type_name -> echoDMS.CollaboratorRole
	3,  // 16: echoDMS.UpdateCollaboratorRequest.role:type_name -> echoDMS.CollaboratorRole
	4,  // 17: echoDMS.UpdateCollaboratorRequest.status:type_name -> echoDMS.CollaboratorStatus
	8,  // 18: echoDMS.ListVersionsResponse.versions:type_name -> echoDMS.DocumentVersion
	9,  // 19: echoDMS.ListCompiledOutputsResponse.outputs:type_name -> echoDMS.CompiledOutput
	13, // 20: echoDMS.PageService.CreatePage:input_type -> echoDMS.CreatePageRequest
	10, // 21: echoDMS.PageService.GetPage:input_type -> echoDMS.GetPageRequest
	11, // 22: echoDMS.PageService.ListPages:input_type -> echoDMS.ListPagesRequest
	14, // 23: echoDMS.PageService.UpdatePage:input_type -> echoDMS.UpdatePageRequest
	15, // 24: echoDMS.PageService.DeletePage:input_type -> echoDMS.DeletePageRequest
	19, // 25: echoDMS.CollaboratorService.AddCollaborator:input_type -> echoDMS.AddCollaboratorRequest
	16, // 26: echoDMS.CollaboratorService.GetCollaborator:input_type -> echoDMS.GetCollaboratorRequest
	17, // 27: echoDMS.CollaboratorService.ListCollaborators:input_type -> echoDMS.ListCollaboratorsRequest
	20, // 28: echoDMS.CollaboratorService.UpdateCollaborator:input_type -> echoDMS.UpdateCollaboratorRequest
	21, // 29: echoDMS.CollaboratorService.RemoveCollaborator:input_type -> echoDMS.RemoveCollaboratorRequest
	25, // 30: echoDMS.VersionService.CreateVersion:input_type -> echoDMS.CreateVersionRequest
	22, // 31: echoDMS.VersionService.GetVersion:input_type -> echoDMS.GetVersionRequest
	23, // 32: echoDMS.VersionService.ListVersions:input_type -> echoDMS.ListVersionsRequest
	26, // 33: echoDMS.CompiledOutputService.GetCompiledOutput:input_type -> echoDMS.GetCompiledOutputRequest
	27, // 34: echoDMS.CompiledOutputService.ListCompiledOutputs:input_type -> echoDMS.ListCompiledOutputsRequest
	6,  // 35: echoDMS.PageService.CreatePage:output_type -> echoDMS.Page
	6,  // 36: echoDMS.PageService.GetPage:output_type -> echoDMS.Page
	12, // 37: echoDMS.PageService.ListPages:output_type -> echoDMS.ListPagesResponse
	6,  // 38: echoDMS.PageService.UpdatePage:output_type -> echoDMS.Page
	30, // 39: echoDMS.PageService.DeletePage:output_type -> google.protobuf.Empty
	7,  // 40: echoDMS.CollaboratorService.AddCollaborator:output_type -> echoDMS.DocumentCollaborator
	7,  // 41: echoDMS.CollaboratorService.GetCollaborator:output_type -> echoDMS.DocumentCollaborator
	18, // 42: echoDMS.CollaboratorService.ListCollaborators:output_type -> echoDMS.ListCollaboratorsResponse
	7,  // 43: echoDMS.CollaboratorService.UpdateCollaborator:output_type -> echoDMS.DocumentCollaborator
	30, // 44: echoDMS.CollaboratorService.RemoveCollaborator:output_type -> google.protobuf.Empty
	8,  // 45: echoDMS.VersionService.CreateVersion:output_type -> echoDMS.DocumentVersion
	8,  // 46: echoDMS.VersionService.GetVersion:output_type -> echoDMS.DocumentVersion
	24, // 47: echoDMS.VersionService.ListVersions:output_type -> echoDMS.ListVersionsResponse
	9,  // 48: echoDMS.CompiledOutputService.GetCompiledOutput:output_type -> echoDMS.CompiledOutput
	28, // 49: echoDMS.CompiledOutputService.ListCompiledOutputs:output_type -> echoDMS.ListCompiledOutputsResponse
	35, // [35:50] is the sub-list for method output_type
	20, // [20:35] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_echodms_proto_init() }
func file_echodms_proto_init() {
	if File_echodms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echodms_proto_rawDesc), len(file_echodms_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_echodms_proto_goTypes,
		DependencyIndexes: file_echodms_proto_depIdxs,
		EnumInfos:         file_echodms_proto_enumTypes,
		MessageInfos:      file_echodms_proto_msgTypes,
	}.Build()
	File_echodms_proto = out.File
	file_echodms_proto_goTypes = nil
	file_echodms_proto_depIdxs = nil
}
