// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: echodms.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PageService_CreatePage_FullMethodName = "/echoDMS.PageService/CreatePage"
	PageService_GetPage_FullMethodName    = "/echoDMS.PageService/GetPage"
	PageService_ListPages_FullMethodName  = "/echoDMS.PageService/ListPages"
	PageService_UpdatePage_FullMethodName = "/echoDMS.PageService/UpdatePage"
	PageService_DeletePage_FullMethodName = "/echoDMS.PageService/DeletePage"
)

// PageServiceClient is the client API for PageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PageServiceClient interface {
	CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*Page, error)
	GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*Page, error)
	ListPages(ctx context.Context, in *ListPagesRequest, opts ...grpc.CallOption) (*ListPagesResponse, error)
	UpdatePage(ctx context.Context, in *UpdatePageRequest, opts ...grpc.CallOption) (*Page, error)
	DeletePage(ctx context.Context, in *DeletePageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type pageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPageServiceClient(cc grpc.ClientConnInterface) PageServiceClient {
	return &pageServiceClient{cc}
}

func (c *pageServiceClient) CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*Page, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Page)
	err := c.cc.Invoke(ctx, PageService_CreatePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*Page, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Page)
	err := c.cc.Invoke(ctx, PageService_GetPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) ListPages(ctx context.Context, in *ListPagesRequest, opts ...grpc.CallOption) (*ListPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPagesResponse)
	err := c.cc.Invoke(ctx, PageService_ListPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) UpdatePage(ctx context.Context, in *UpdatePageRequest, opts ...grpc.CallOption) (*Page, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Page)
	err := c.cc.Invoke(ctx, PageService_UpdatePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) DeletePage(ctx context.Context, in *DeletePageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PageService_DeletePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PageServiceServer is the server API for PageService service.
// All implementations must embed UnimplementedPageServiceServer
// for forward compatibility.
type PageServiceServer interface {
	CreatePage(context.Context, *CreatePageRequest) (*Page, error)
	GetPage(context.Context, *GetPageRequest) (*Page, error)
	ListPages(context.Context, *ListPagesRequest) (*ListPagesResponse, error)
	UpdatePage(context.Context, *UpdatePageRequest) (*Page, error)
	DeletePage(context.Context, *DeletePageRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPageServiceServer()
}

// UnimplementedPageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPageServiceServer struct{}

func (UnimplementedPageServiceServer) CreatePage(context.Context, *CreatePageRequest) (*Page, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePage not implemented")
}
func (UnimplementedPageServiceServer) GetPage(context.Context, *GetPageRequest) (*Page, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPage not implemented")
}
func (UnimplementedPageServiceServer) ListPages(context.Context, *ListPagesRequest) (*ListPagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPages not implemented")
}
func (UnimplementedPageServiceServer) UpdatePage(context.Context, *UpdatePageRequest) (*Page, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePage not implemented")
}
func (UnimplementedPageServiceServer) DeletePage(context.Context, *DeletePageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePage not implemented")
}
func (UnimplementedPageServiceServer) mustEmbedUnimplementedPageServiceServer() {}
func (UnimplementedPageServiceServer) testEmbeddedByValue()                     {}

// UnsafePageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PageServiceServer will
// result in compilation errors.
type UnsafePageServiceServer interface {
	mustEmbedUnimplementedPageServiceServer()
}

func RegisterPageServiceServer(s grpc.ServiceRegistrar, srv PageServiceServer) {
	// If the following call panics, it indicates UnimplementedPageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PageService_ServiceDesc, srv)
}

func _PageService_CreatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).CreatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_CreatePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).CreatePage(ctx, req.(*CreatePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_GetPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).GetPage(ctx, req.(*GetPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_ListPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).ListPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_ListPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).ListPages(ctx, req.(*ListPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_UpdatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).UpdatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_UpdatePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).UpdatePage(ctx, req.(*UpdatePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_DeletePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).DeletePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_DeletePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).DeletePage(ctx, req.(*DeletePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PageService_ServiceDesc is the grpc.ServiceDesc for PageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echoDMS.PageService",
	HandlerType: (*PageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePage",
			Handler:    _PageService_CreatePage_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _PageService_GetPage_Handler,
		},
		{
			MethodName: "ListPages",
			Handler:    _PageService_ListPages_Handler,
		},
		{
			MethodName: "UpdatePage",
			Handler:    _PageService_UpdatePage_Handler,
		},
		{
			MethodName: "DeletePage",
			Handler:    _PageService_DeletePage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echodms.proto",
}

const (
	CollaboratorService_AddCollaborator_FullMethodName    = "/echoDMS.CollaboratorService/AddCollaborator"
	CollaboratorService_GetCollaborator_FullMethodName    = "/echoDMS.CollaboratorService/GetCollaborator"
	CollaboratorService_ListCollaborators_FullMethodName  = "/echoDMS.CollaboratorService/ListCollaborators"
	CollaboratorService_UpdateCollaborator_FullMethodName = "/echoDMS.CollaboratorService/UpdateCollaborator"
	CollaboratorService_RemoveCollaborator_FullMethodName = "/echoDMS.CollaboratorService/RemoveCollaborator"
)

// CollaboratorServiceClient is the client API for CollaboratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollaboratorServiceClient interface {
	AddCollaborator(ctx context.Context, in *AddCollaboratorRequest, opts ...grpc.CallOption) (*DocumentCollaborator, error)
	GetCollaborator(ctx context.Context, in *GetCollaboratorRequest, opts ...grpc.CallOption) (*DocumentCollaborator, error)
	ListCollaborators(ctx context.Context, in *ListCollaboratorsRequest, opts ...grpc.CallOption) (*ListCollaboratorsResponse, error)
	UpdateCollaborator(ctx context.Context, in *UpdateCollaboratorRequest, opts ...grpc.CallOption) (*DocumentCollaborator, error)
	RemoveCollaborator(ctx context.Context, in *RemoveCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type collaboratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollaboratorServiceClient(cc grpc.ClientConnInterface) CollaboratorServiceClient {
	return &collaboratorServiceClient{cc}
}

func (c *collaboratorServiceClient) AddCollaborator(ctx context.Context, in *AddCollaboratorRequest, opts ...grpc.CallOption) (*DocumentCollaborator, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentCollaborator)
	err := c.cc.Invoke(ctx, CollaboratorService_AddCollaborator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collaboratorServiceClient) GetCollaborator(ctx context.Context, in *GetCollaboratorRequest, opts ...grpc.CallOption) (*DocumentCollaborator, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentCollaborator)
	err := c.cc.Invoke(ctx, CollaboratorService_GetCollaborator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collaboratorServiceClient) ListCollaborators(ctx context.Context, in *ListCollaboratorsRequest, opts ...grpc.CallOption) (*ListCollaboratorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollaboratorsResponse)
	err := c.cc.Invoke(ctx, CollaboratorService_ListCollaborators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collaboratorServiceClient) UpdateCollaborator(ctx context.Context, in *UpdateCollaboratorRequest, opts ...grpc.CallOption) (*DocumentCollaborator, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentCollaborator)
	err := c.cc.Invoke(ctx, CollaboratorService_UpdateCollaborator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collaboratorServiceClient) RemoveCollaborator(ctx context.Context, in *RemoveCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CollaboratorService_RemoveCollaborator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollaboratorServiceServer is the server API for CollaboratorService service.
// All implementations must embed UnimplementedCollaboratorServiceServer
// for forward compatibility.
type CollaboratorServiceServer interface {
	AddCollaborator(context.Context, *AddCollaboratorRequest) (*DocumentCollaborator, error)
	GetCollaborator(context.Context, *GetCollaboratorRequest) (*DocumentCollaborator, error)
	ListCollaborators(context.Context, *ListCollaboratorsRequest) (*ListCollaboratorsResponse, error)
	UpdateCollaborator(context.Context, *UpdateCollaboratorRequest) (*DocumentCollaborator, error)
	RemoveCollaborator(context.Context, *RemoveCollaboratorRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCollaboratorServiceServer()
}

// UnimplementedCollaboratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollaboratorServiceServer struct{}

func (UnimplementedCollaboratorServiceServer) AddCollaborator(context.Context, *AddCollaboratorRequest) (*DocumentCollaborator, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCollaborator not implemented")
}
func (UnimplementedCollaboratorServiceServer) GetCollaborator(context.Context, *GetCollaboratorRequest) (*DocumentCollaborator, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollaborator not implemented")
}
func (UnimplementedCollaboratorServiceServer) ListCollaborators(context.Context, *ListCollaboratorsRequest) (*ListCollaboratorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollaborators not implemented")
}
func (UnimplementedCollaboratorServiceServer) UpdateCollaborator(context.Context, *UpdateCollaboratorRequest) (*DocumentCollaborator, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCollaborator not implemented")
}
func (UnimplementedCollaboratorServiceServer) RemoveCollaborator(context.Context, *RemoveCollaboratorRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveCollaborator not implemented")
}
func (UnimplementedCollaboratorServiceServer) mustEmbedUnimplementedCollaboratorServiceServer() {}
func (UnimplementedCollaboratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeCollaboratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollaboratorServiceServer will
// result in compilation errors.
type UnsafeCollaboratorServiceServer interface {
	mustEmbedUnimplementedCollaboratorServiceServer()
}

func RegisterCollaboratorServiceServer(s grpc.ServiceRegistrar, srv CollaboratorServiceServer) {
	// If the following call panics, it indicates UnimplementedCollaboratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollaboratorService_ServiceDesc, srv)
}

func _CollaboratorService_AddCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollaboratorServiceServer).AddCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollaboratorService_AddCollaborator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollaboratorServiceServer).AddCollaborator(ctx, req.(*AddCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollaboratorService_GetCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollaboratorServiceServer).GetCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollaboratorService_GetCollaborator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollaboratorServiceServer).GetCollaborator(ctx, req.(*GetCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollaboratorService_ListCollaborators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollaboratorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollaboratorServiceServer).ListCollaborators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollaboratorService_ListCollaborators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollaboratorServiceServer).ListCollaborators(ctx, req.(*ListCollaboratorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollaboratorService_UpdateCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollaboratorServiceServer).UpdateCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollaboratorService_UpdateCollaborator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollaboratorServiceServer).UpdateCollaborator(ctx, req.(*UpdateCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollaboratorService_RemoveCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollaboratorServiceServer).RemoveCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollaboratorService_RemoveCollaborator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollaboratorServiceServer).RemoveCollaborator(ctx, req.(*RemoveCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollaboratorService_ServiceDesc is the grpc.ServiceDesc for CollaboratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollaboratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echoDMS.CollaboratorService",
	HandlerType: (*CollaboratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCollaborator",
			Handler:    _CollaboratorService_AddCollaborator_Handler,
		},
		{
			MethodName: "GetCollaborator",
			Handler:    _CollaboratorService_GetCollaborator_Handler,
		},
		{
			MethodName: "ListCollaborators",
			Handler:    _CollaboratorService_ListCollaborators_Handler,
		},
		{
			MethodName: "UpdateCollaborator",
			Handler:    _CollaboratorService_UpdateCollaborator_Handler,
		},
		{
			MethodName: "RemoveCollaborator",
			Handler:    _CollaboratorService_RemoveCollaborator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echodms.proto",
}

const (
	VersionService_CreateVersion_FullMethodName = "/echoDMS.VersionService/CreateVersion"
	VersionService_GetVersion_FullMethodName    = "/echoDMS.VersionService/GetVersion"
	VersionService_ListVersions_FullMethodName  = "/echoDMS.VersionService/ListVersions"
)

// VersionServiceClient is the client API for VersionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VersionServiceClient interface {
	CreateVersion(ctx context.Context, in *CreateVersionRequest, opts ...grpc.CallOption) (*DocumentVersion, error)
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*DocumentVersion, error)
	ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error)
}

type versionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVersionServiceClient(cc grpc.ClientConnInterface) VersionServiceClient {
	return &versionServiceClient{cc}
}

func (c *versionServiceClient) CreateVersion(ctx context.Context, in *CreateVersionRequest, opts ...grpc.CallOption) (*DocumentVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentVersion)
	err := c.cc.Invoke(ctx, VersionService_CreateVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*DocumentVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentVersion)
	err := c.cc.Invoke(ctx, VersionService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionServiceClient) ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVersionsResponse)
	err := c.cc.Invoke(ctx, VersionService_ListVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersionServiceServer is the server API for VersionService service.
// All implementations must embed UnimplementedVersionServiceServer
// for forward compatibility.
type VersionServiceServer interface {
	CreateVersion(context.Context, *CreateVersionRequest) (*DocumentVersion, error)
	GetVersion(context.Context, *GetVersionRequest) (*DocumentVersion, error)
	ListVersions(context.Context, *ListVersionsRequest) (*ListVersionsResponse, error)
	mustEmbedUnimplementedVersionServiceServer()
}

// UnimplementedVersionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVersionServiceServer struct{}

func (UnimplementedVersionServiceServer) CreateVersion(context.Context, *CreateVersionRequest) (*DocumentVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVersion not implemented")
}
func (UnimplementedVersionServiceServer) GetVersion(context.Context, *GetVersionRequest) (*DocumentVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedVersionServiceServer) ListVersions(context.Context, *ListVersionsRequest) (*ListVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVersions not implemented")
}
func (UnimplementedVersionServiceServer) mustEmbedUnimplementedVersionServiceServer() {}
func (UnimplementedVersionServiceServer) testEmbeddedByValue()                        {}

// UnsafeVersionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VersionServiceServer will
// result in compilation errors.
type UnsafeVersionServiceServer interface {
	mustEmbedUnimplementedVersionServiceServer()
}

func RegisterVersionServiceServer(s grpc.ServiceRegistrar, srv VersionServiceServer) {
	// If the following call panics, it indicates UnimplementedVersionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VersionService_ServiceDesc, srv)
}

func _VersionService_CreateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServiceServer).CreateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionService_CreateVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServiceServer).CreateVersion(ctx, req.(*CreateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionService_ListVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServiceServer).ListVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionService_ListVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServiceServer).ListVersions(ctx, req.(*ListVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VersionService_ServiceDesc is the grpc.ServiceDesc for VersionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VersionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echoDMS.VersionService",
	HandlerType: (*VersionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVersion",
			Handler:    _VersionService_CreateVersion_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _VersionService_GetVersion_Handler,
		},
		{
			MethodName: "ListVersions",
			Handler:    _VersionService_ListVersions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echodms.proto",
}

const (
	CompiledOutputService_GetCompiledOutput_FullMethodName   = "/echoDMS.CompiledOutputService/GetCompiledOutput"
	CompiledOutputService_ListCompiledOutputs_FullMethodName = "/echoDMS.CompiledOutputService/ListCompiledOutputs"
)

// CompiledOutputServiceClient is the client API for CompiledOutputService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompiledOutputServiceClient interface {
	GetCompiledOutput(ctx context.Context, in *GetCompiledOutputRequest, opts ...grpc.CallOption) (*CompiledOutput, error)
	ListCompiledOutputs(ctx context.Context, in *ListCompiledOutputsRequest, opts ...grpc.CallOption) (*ListCompiledOutputsResponse, error)
}

type compiledOutputServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompiledOutputServiceClient(cc grpc.ClientConnInterface) CompiledOutputServiceClient {
	return &compiledOutputServiceClient{cc}
}

func (c *compiledOutputServiceClient) GetCompiledOutput(ctx context.Context, in *GetCompiledOutputRequest, opts ...grpc.CallOption) (*CompiledOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompiledOutput)
	err := c.cc.Invoke(ctx, CompiledOutputService_GetCompiledOutput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compiledOutputServiceClient) ListCompiledOutputs(ctx context.Context, in *ListCompiledOutputsRequest, opts ...grpc.CallOption) (*ListCompiledOutputsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCompiledOutputsResponse)
	err := c.cc.Invoke(ctx, CompiledOutputService_ListCompiledOutputs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompiledOutputServiceServer is the server API for CompiledOutputService service.
// All implementations must embed UnimplementedCompiledOutputServiceServer
// for forward compatibility.
type CompiledOutputServiceServer interface {
	GetCompiledOutput(context.Context, *GetCompiledOutputRequest) (*CompiledOutput, error)
	ListCompiledOutputs(context.Context, *ListCompiledOutputsRequest) (*ListCompiledOutputsResponse, error)
	mustEmbedUnimplementedCompiledOutputServiceServer()
}

// UnimplementedCompiledOutputServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompiledOutputServiceServer struct{}

func (UnimplementedCompiledOutputServiceServer) GetCompiledOutput(context.Context, *GetCompiledOutputRequest) (*CompiledOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompiledOutput not implemented")
}
func (UnimplementedCompiledOutputServiceServer) ListCompiledOutputs(context.Context, *ListCompiledOutputsRequest) (*ListCompiledOutputsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCompiledOutputs not implemented")
}
func (UnimplementedCompiledOutputServiceServer) mustEmbedUnimplementedCompiledOutputServiceServer() {}
func (UnimplementedCompiledOutputServiceServer) testEmbeddedByValue()                               {}

// UnsafeCompiledOutputServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompiledOutputServiceServer will
// result in compilation errors.
type UnsafeCompiledOutputServiceServer interface {
	mustEmbedUnimplementedCompiledOutputServiceServer()
}

func RegisterCompiledOutputServiceServer(s grpc.ServiceRegistrar, srv CompiledOutputServiceServer) {
	// If the following call panics, it indicates UnimplementedCompiledOutputServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompiledOutputService_ServiceDesc, srv)
}

func _CompiledOutputService_GetCompiledOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompiledOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompiledOutputServiceServer).GetCompiledOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompiledOutputService_GetCompiledOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompiledOutputServiceServer).GetCompiledOutput(ctx, req.(*GetCompiledOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompiledOutputService_ListCompiledOutputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCompiledOutputsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompiledOutputServiceServer).ListCompiledOutputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompiledOutputService_ListCompiledOutputs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompiledOutputServiceServer).ListCompiledOutputs(ctx, req.(*ListCompiledOutputsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompiledOutputService_ServiceDesc is the grpc.ServiceDesc for CompiledOutputService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompiledOutputService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echoDMS.CompiledOutputService",
	HandlerType: (*CompiledOutputServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCompiledOutput",
			Handler:    _CompiledOutputService_GetCompiledOutput_Handler,
		},
		{
			MethodName: "ListCompiledOutputs",
			Handler:    _CompiledOutputService_ListCompiledOutputs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echodms.proto",
}
