// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/document/document.proto

package document

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentFormat int32

const (
	DocumentFormat_DOCUMENT_FORMAT_UNSPECIFIED DocumentFormat = 0
	DocumentFormat_TYPST                       DocumentFormat = 1
	DocumentFormat_LATEX                       DocumentFormat = 2
	DocumentFormat_MARKDOWN                    DocumentFormat = 3
)

// Enum value maps for DocumentFormat.
var (
	DocumentFormat_name = map[int32]string{
		0: "DOCUMENT_FORMAT_UNSPECIFIED",
		1: "TYPST",
		2: "LATEX",
		3: "MARKDOWN",
	}
	DocumentFormat_value = map[string]int32{
		"DOCUMENT_FORMAT_UNSPECIFIED": 0,
		"TYPST":                       1,
		"LATEX":                       2,
		"MARKDOWN":                    3,
	}
)

func (x DocumentFormat) Enum() *DocumentFormat {
	p := new(DocumentFormat)
	*p = x
	return p
}

func (x DocumentFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_document_document_proto_enumTypes[0].Descriptor()
}

func (DocumentFormat) Type() protoreflect.EnumType {
	return &file_proto_document_document_proto_enumTypes[0]
}

func (x DocumentFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentFormat.Descriptor instead.
func (DocumentFormat) EnumDescriptor() ([]byte, []int) {
	return file_proto_document_document_proto_rawDescGZIP(), []int{0}
}

type CompilerName int32

const (
	CompilerName_COMPILER_NAME_UNSPECIFIED CompilerName = 0
	CompilerName_TYPST_COMPILER            CompilerName = 1
	CompilerName_PDFLATEX                  CompilerName = 2
	CompilerName_XELATEX                   CompilerName = 3
	CompilerName_LUALATEX                  CompilerName = 4
	CompilerName_PANDOC                    CompilerName = 5
)

// Enum value maps for CompilerName.
var (
	CompilerName_name = map[int32]string{
		0: "COMPILER_NAME_UNSPECIFIED",
		1: "TYPST_COMPILER",
		2: "PDFLATEX",
		3: "XELATEX",
		4: "LUALATEX",
		5: "PANDOC",
	}
	CompilerName_value = map[string]int32{
		"COMPILER_NAME_UNSPECIFIED": 0,
		"TYPST_COMPILER":            1,
		"PDFLATEX":                  2,
		"XELATEX":                   3,
		"LUALATEX":                  4,
		"PANDOC":                    5,
	}
)

func (x CompilerName) Enum() *CompilerName {
	p := new(CompilerName)
	*p = x
	return p
}

func (x CompilerName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompilerName) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_document_document_proto_enumTypes[1].Descriptor()
}

func (CompilerName) Type() protoreflect.EnumType {
	return &file_proto_document_document_proto_enumTypes[1]
}

func (x CompilerName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompilerName.Descriptor instead.
func (CompilerName) EnumDescriptor() ([]byte, []int) {
	return file_proto_document_document_proto_rawDescGZIP(), []int{1}
}

type OutputFormat int32

const (
	OutputFormat_OUTPUT_FORMAT_UNSPECIFIED OutputFormat = 0
	OutputFormat_PDF                       OutputFormat = 1
	OutputFormat_PNG                       OutputFormat = 2
	OutputFormat_SVG                       OutputFormat = 3
	OutputFormat_HTML                      OutputFormat = 4
)

// Enum value maps for OutputFormat.
var (
	OutputFormat_name = map[int32]string{
		0: "OUTPUT_FORMAT_UNSPECIFIED",
		1: "PDF",
		2: "PNG",
		3: "SVG",
		4: "HTML",
	}
	OutputFormat_value = map[string]int32{
		"OUTPUT_FORMAT_UNSPECIFIED": 0,
		"PDF":                       1,
		"PNG":                       2,
		"SVG":                       3,
		"HTML":                      4,
	}
)

func (x OutputFormat) Enum() *OutputFormat {
	p := new(OutputFormat)
	*p = x
	return p
}

func (x OutputFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_document_document_proto_enumTypes[2].Descriptor()
}

func (OutputFormat) Type() protoreflect.EnumType {
	return &file_proto_document_document_proto_enumTypes[2]
}

func (x OutputFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputFormat.Descriptor instead.
func (OutputFormat) EnumDescriptor() ([]byte, []int) {
	return file_proto_document_document_proto_rawDescGZIP(), []int{2}
}

type Document struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Format          DocumentFormat         `protobuf:"varint,4,opt,name=format,proto3,enum=document.DocumentFormat" json:"format,omitempty"`
	Compiler        CompilerName           `protobuf:"varint,5,opt,name=compiler,proto3,enum=document.CompilerName" json:"compiler,omitempty"`
	CompilerVersion string                 `protobuf:"bytes,6,opt,name=compiler_version,json=compilerVersion,proto3" json:"compiler_version,omitempty"`
	OutputFormat    OutputFormat           `protobuf:"varint,7,opt,name=output_format,json=outputFormat,proto3,enum=document.OutputFormat" json:"output_format,omitempty"`
	OwnerId         string                 `protobuf:"bytes,8,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	IsArchived      bool                   `protobuf:"varint,9,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_document_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_document_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Document) GetFormat() DocumentFormat {
	if x != nil {
		return x.Format
	}
	return DocumentFormat_DOCUMENT_FORMAT_UNSPECIFIED
}

func (x *Document) GetCompiler() CompilerName {
	if x != nil {
		return x.Compiler
	}
	return CompilerName_COMPILER_NAME_UNSPECIFIED
}

func (x *Document) GetCompilerVersion() string {
	if x != nil {
		return x.CompilerVersion
	}
	return ""
}

func (x *Document) GetOutputFormat() OutputFormat {
	if x != nil {
		return x.OutputFormat
	}
	return OutputFormat_OUTPUT_FORMAT_UNSPECIFIED
}

func (x *Document) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Document) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_proto_document_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_document_proto_rawDescGZIP(), []int{1}
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_proto_document_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_document_proto_rawDescGZIP(), []int{2}
}

func (x *GetDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type PaginateDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginateDocumentsRequest) Reset() {
	*x = PaginateDocumentsRequest{}
	mi := &file_proto_document_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginateDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginateDocumentsRequest) ProtoMessage() {}

func (x *PaginateDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginateDocumentsRequest.ProtoReflect.Descriptor instead.
func (*PaginateDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_document_proto_rawDescGZIP(), []int{3}
}

func (x *PaginateDocumentsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *PaginateDocumentsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *PaginateDocumentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaginateDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginateDocumentsResponse) Reset() {
	*x = PaginateDocumentsResponse{}
	mi := &file_proto_document_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginateDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginateDocumentsResponse) ProtoMessage() {}

func (x *PaginateDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginateDocumentsResponse.ProtoReflect.Descriptor instead.
func (*PaginateDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_document_proto_rawDescGZIP(), []int{4}
}

func (x *PaginateDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

type CreateDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Format          DocumentFormat         `protobuf:"varint,3,opt,name=format,proto3,enum=document.DocumentFormat" json:"format,omitempty"`
	Compiler        CompilerName           `protobuf:"varint,4,opt,name=compiler,proto3,enum=document.CompilerName" json:"compiler,omitempty"`
	CompilerVersion string                 `protobuf:"bytes,5,opt,name=compiler_version,json=compilerVersion,proto3" json:"compiler_version,omitempty"`
	OutputFormat    OutputFormat           `protobuf:"varint,6,opt,name=output_format,json=outputFormat,proto3,enum=document.OutputFormat" json:"output_format,omitempty"`
	OwnerId         string                 `protobuf:"bytes,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_proto_document_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_document_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDocumentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDocumentRequest) GetFormat() DocumentFormat {
	if x != nil {
		return x.Format
	}
	return DocumentFormat_DOCUMENT_FORMAT_UNSPECIFIED
}

func (x *CreateDocumentRequest) GetCompiler() CompilerName {
	if x != nil {
		return x.Compiler
	}
	return CompilerName_COMPILER_NAME_UNSPECIFIED
}

func (x *CreateDocumentRequest) GetCompilerVersion() string {
	if x != nil {
		return x.CompilerVersion
	}
	return ""
}

func (x *CreateDocumentRequest) GetOutputFormat() OutputFormat {
	if x != nil {
		return x.OutputFormat
	}
	return OutputFormat_OUTPUT_FORMAT_UNSPECIFIED
}

func (x *CreateDocumentRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type UpdateDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Format          DocumentFormat         `protobuf:"varint,4,opt,name=format,proto3,enum=document.DocumentFormat" json:"format,omitempty"`
	Compiler        CompilerName           `protobuf:"varint,5,opt,name=compiler,proto3,enum=document.CompilerName" json:"compiler,omitempty"`
	CompilerVersion string                 `protobuf:"bytes,6,opt,name=compiler_version,json=compilerVersion,proto3" json:"compiler_version,omitempty"`
	OutputFormat    OutputFormat           `protobuf:"varint,7,opt,name=output_format,json=outputFormat,proto3,enum=document.OutputFormat" json:"output_format,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_proto_document_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_document_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDocumentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateDocumentRequest) GetFormat() DocumentFormat {
	if x != nil {
		return x.Format
	}
	return DocumentFormat_DOCUMENT_FORMAT_UNSPECIFIED
}

func (x *UpdateDocumentRequest) GetCompiler() CompilerName {
	if x != nil {
		return x.Compiler
	}
	return CompilerName_COMPILER_NAME_UNSPECIFIED
}

func (x *UpdateDocumentRequest) GetCompilerVersion() string {
	if x != nil {
		return x.CompilerVersion
	}
	return ""
}

func (x *UpdateDocumentRequest) GetOutputFormat() OutputFormat {
	if x != nil {
		return x.OutputFormat
	}
	return OutputFormat_OUTPUT_FORMAT_UNSPECIFIED
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_proto_document_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_document_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentsRequest) Reset() {
	*x = DeleteDocumentsRequest{}
	mi := &file_proto_document_document_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentsRequest) ProtoMessage() {}

func (x *DeleteDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_document_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentsRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_document_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDocumentsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_proto_document_document_proto protoreflect.FileDescriptor

const file_proto_document_document_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/document/document.proto\x12\bdocument\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd2\x03\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\x06format\x18\x04 \x01(\x0e2\x18.document.DocumentFormatR\x06format\x122\n" +
	"\bcompiler\x18\x05 \x01(\x0e2\x16.document.CompilerNameR\bcompiler\x12)\n" +
	"\x10compiler_version\x18\x06 \x01(\tR\x0fcompilerVersion\x12;\n" +
	"\routput_format\x18\a \x01(\x0e2\x16.document.OutputFormatR\foutputFormat\x12\x19\n" +
	"\bowner_id\x18\b \x01(\tR\aownerId\x12\x1f\n" +
	"\vis_archived\x18\t \x01(\bR\n" +
	"isArchived\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"$\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x13GetDocumentResponse\x12.\n" +
	"\bdocument\x18\x01 \x01(\v2\x12.document.DocumentR\bdocument\"s\n" +
	"\x18PaginateDocumentsRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"M\n" +
	"\x19PaginateDocumentsResponse\x120\n" +
	"\tdocuments\x18\x01 \x03(\v2\x12.document.DocumentR\tdocuments\"\xb8\x02\n" +
	"\x15CreateDocumentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x120\n" +
	"\x06format\x18\x03 \x01(\x0e2\x18.document.DocumentFormatR\x06format\x122\n" +
	"\bcompiler\x18\x04 \x01(\x0e2\x16.document.CompilerNameR\bcompiler\x12)\n" +
	"\x10compiler_version\x18\x05 \x01(\tR\x0fcompilerVersion\x12;\n" +
	"\routput_format\x18\x06 \x01(\x0e2\x16.document.OutputFormatR\foutputFormat\x12\x19\n" +
	"\bowner_id\x18\a \x01(\tR\aownerId\"\xad\x02\n" +
	"\x15UpdateDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\x06format\x18\x04 \x01(\x0e2\x18.document.DocumentFormatR\x06format\x122\n" +
	"\bcompiler\x18\x05 \x01(\x0e2\x16.document.CompilerNameR\bcompiler\x12)\n" +
	"\x10compiler_version\x18\x06 \x01(\tR\x0fcompilerVersion\x12;\n" +
	"\routput_format\x18\a \x01(\x0e2\x16.document.OutputFormatR\foutputFormat\"'\n" +
	"\x15DeleteDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x16DeleteDocumentsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids*U\n" +
	"\x0eDocumentFormat\x12\x1f\n" +
	"\x1bDOCUMENT_FORMAT_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05TYPST\x10\x01\x12\t\n" +
	"\x05LATEX\x10\x02\x12\f\n" +
	"\bMARKDOWN\x10\x03*v\n" +
	"\fCompilerName\x12\x1d\n" +
	"\x19COMPILER_NAME_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTYPST_COMPILER\x10\x01\x12\f\n" +
	"\bPDFLATEX\x10\x02\x12\v\n" +
	"\aXELATEX\x10\x03\x12\f\n" +
	"\bLUALATEX\x10\x04\x12\n" +
	"\n" +
	"\x06PANDOC\x10\x05*R\n" +
	"\fOutputFormat\x12\x1d\n" +
	"\x19OUTPUT_FORMAT_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03PDF\x10\x01\x12\a\n" +
	"\x03PNG\x10\x02\x12\a\n" +
	"\x03SVG\x10\x03\x12\b\n" +
	"\x04HTML\x10\x042\xe1\x03\n" +
	"\x0fDocumentService\x12J\n" +
	"\vGetDocument\x12\x1c.document.GetDocumentRequest\x1a\x1d.document.GetDocumentResponse\x12\\\n" +
	"\x11PaginateDocuments\x12\".document.PaginateDocumentsRequest\x1a#.document.PaginateDocumentsResponse\x12E\n" +
	"\x0eCreateDocument\x12\x1f.document.CreateDocumentRequest\x1a\x12.document.Document\x12E\n" +
	"\x0eUpdateDocument\x12\x1f.document.UpdateDocumentRequest\x1a\x12.document.Document\x12I\n" +
	"\x0eDeleteDocument\x12\x1f.document.DeleteDocumentRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x0fDeleteDocuments\x12 .document.DeleteDocumentsRequest\x1a\x16.google.protobuf.EmptyB#Z!github.com/echoDMS/proto/documentb\x06proto3"

var (
	file_proto_document_document_proto_rawDescOnce sync.Once
	file_proto_document_document_proto_rawDescData []byte
)

func file_proto_document_document_proto_rawDescGZIP() []byte {
	file_proto_document_document_proto_rawDescOnce.Do(func() {
		file_proto_document_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_document_document_proto_rawDesc), len(file_proto_document_document_proto_rawDesc)))
	})
	return file_proto_document_document_proto_rawDescData
}

var file_proto_document_document_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_document_document_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_document_document_proto_goTypes = []any{
	(DocumentFormat)(0),               // 0: document.DocumentFormat
	(CompilerName)(0),                 // 1: document.CompilerName
	(OutputFormat)(0),                 // 2: document.OutputFormat
	(*Document)(nil),                  // 3: document.Document
	(*GetDocumentRequest)(nil),        // 4: document.GetDocumentRequest
	(*GetDocumentResponse)(nil),       // 5: document.GetDocumentResponse
	(*PaginateDocumentsRequest)(nil),  // 6: document.PaginateDocumentsRequest
	(*PaginateDocumentsResponse)(nil), // 7: document.PaginateDocumentsResponse
	(*CreateDocumentRequest)(nil),     // 8: document.CreateDocumentRequest
	(*UpdateDocumentRequest)(nil),     // 9: document.UpdateDocumentRequest
	(*DeleteDocumentRequest)(nil),     // 10: document.DeleteDocumentRequest
	(*DeleteDocumentsRequest)(nil),    // 11: document.DeleteDocumentsRequest
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 13: google.protobuf.Empty
}
var file_proto_document_document_proto_depIdxs = []int32{
	0,  // 0: document.Document.format:type_name -> document.DocumentFormat
	1,  // 1: document.Document.compiler:type_name -> document.CompilerName
	2,  // 2: document.Document.output_format:type_name -> document.OutputFormat
	12, // 3: document.Document.created_at:type_name -> google.protobuf.Timestamp
	12, // 4: document.Document.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 5: document.GetDocumentResponse.document:type_name -> document.Document
	3,  // 6: document.PaginateDocumentsResponse.documents:type_name -> document.Document
	0,  // 7: document.CreateDocumentRequest.format:type_name -> document.DocumentFormat
	1,  // 8: document.CreateDocumentRequest.compiler:type_name -> document.CompilerName
	2,  // 9: document.CreateDocumentRequest.output_format:type_name -> document.OutputFormat
	0,  // 10: document.UpdateDocumentRequest.format:type_name -> document.DocumentFormat
	1,  // 11: document.UpdateDocumentRequest.compiler:type_name -> document.CompilerName
	2,  // 12: document.UpdateDocumentRequest.output_format:type_name -> document.OutputFormat
	4,  // 13: document.DocumentService.GetDocument:input_type -> document.GetDocumentRequest
	6,  // 14: document.DocumentService.PaginateDocuments:input_type -> document.PaginateDocumentsRequest
	8,  // 15: document.DocumentService.CreateDocument:input_type -> document.CreateDocumentRequest
	9,  // 16: document.DocumentService.UpdateDocument:input_type -> document.UpdateDocumentRequest
	10, // 17: document.DocumentService.DeleteDocument:input_type -> document.DeleteDocumentRequest
	11, // 18: document.DocumentService.DeleteDocuments:input_type -> document.DeleteDocumentsRequest
	5,  // 19: document.DocumentService.GetDocument:output_type -> document.GetDocumentResponse
	7,  // 20: document.DocumentService.PaginateDocuments:output_type -> document.PaginateDocumentsResponse
	3,  // 21: document.DocumentService.CreateDocument:output_type -> document.Document
	3,  // 22: document.DocumentService.UpdateDocument:output_type -> document.Document
	13, // 23: document.DocumentService.DeleteDocument:output_type -> google.protobuf.Empty
	13, // 24: document.DocumentService.DeleteDocuments:output_type -> google.protobuf.Empty
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_document_document_proto_init() }
func file_proto_document_document_proto_init() {
	if File_proto_document_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_document_document_proto_rawDesc), len(file_proto_document_document_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_document_document_proto_goTypes,
		DependencyIndexes: file_proto_document_document_proto_depIdxs,
		EnumInfos:         file_proto_document_document_proto_enumTypes,
		MessageInfos:      file_proto_document_document_proto_msgTypes,
	}.Build()
	File_proto_document_document_proto = out.File
	file_proto_document_document_proto_goTypes = nil
	file_proto_document_document_proto_depIdxs = nil
}
